[package]
name = "rust-snake"
version = "0.1.0"
authors = ["James Patrick Keegan <atomicbomber.email@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "*"
piston2d-graphics = "*"
rand = "*"